Added support for regional secrets via Google Cloud Secret Manager
micronaut-projects/micronaut-gcp pull request #1202
Opened 2024-10-23 13:19 UTC by abheda-crest

Added support for regional secrets via Google Cloud Secret Manager.

**Approach:**
- We have added a location field in the `SecretManagerConfigurationProperties`
- We have injected the `SecretManagerConfigurationProperties` into the `SecretManagerFactory` using constructor injection. This will be used to create the `SecretManagerServiceClient` based on the location provided in the configuration.
- We have added `DefaultLocationSecretManagerClient` class that will be used to fetch regional secrets based on the location provided in the configuration. For this, we have injected `SecretManagerConfigurationProperties`.
- We have also handled scenario to conditionally generate an implementation of `SecretManagerClient` based on the availability of location property in the configuration using `@Requires` annotation. i.e. If location field is present, than a bean of `DefaultLocationSecretManagerClient` will be created, else a bean of `DefaultSecretManagerClient` will be created.
- We have also added location field to the wrapper class `VersionedSecret`.

**Alternative Approach and the reason we avoided it:**

Rather than developing a separate implementation for the wrapper client `DefaultLocationSecretManagerClient`, we could have introduced a new field for `SecretManagerConfigurationProperties` and utilised constructor injection to modify the existing constructor of the `DefaultSecretManagerClient`. However, we were concerned that some users might have used this constructor to instantiate the wrapper client. As a result, we decided to pursue the approach outlined above.

We've covered the following scenarios for both global as well as regional secrets to test the functionality:
- **Positive**
    - We were able to inject the bean of type SecretManagerServiceClient and fetch the secrets
    - We were able to inject the bean of wrapper client SecretManagerClient and fetch the secrets
    - We were able to load default config when config-client is enabled
    - We were able to load non default config when config-client is enabled
    - We were able to load key/value pairs into a PropertySource when config-client is enabled
- **Negative**
    - When config-client is not enabled, the default config is not loaded
    - When config-client is enabled and the default-config property is false, the default config is not loaded
    - When config-client is not enabled, the non default config is not loaded
    - When config-client is not enabled, the key/value pairs is not loaded into a PropertySource
    - When I added `gcp.secret-manager.location=` to the bootstrap configuration, the SecretManagerServiceClient was created using the global endpoint (https://secretmanager.googleapis.com/). Also, `DefaultLocationSecretManagerClient` was instantiated, rather than the `DefaultSecretManagerClient` itself, which depends on the SecretManagerServiceClient. Consequently, when using the methods of this wrapper location client, we cannot retrieve the regional secrets, and we won’t see any errors. This is because the `getSecret` method manages errors by returning a Mono.empty() object in case of an error.

More information about regional secrets: https://cloud.google.com/secret-manager/regional-secrets/data-residency

2024-10-23 13:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/micronaut-projects/micronaut-gcp?pullRequest=1202) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/micronaut-projects/micronaut-gcp?pullRequest=1202) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/micronaut-projects/micronaut-gcp?pullRequest=1202) it.</sub>

2024-10-23 14:41 UTC, graemerocher requested changes
Nice work! Just a few items to address

2024-10-23 14:41 UTC, graemerocher commented on gcp-secret-manager/src/main/java/io/micronaut/gcp/secretmanager/client/DefaultLocationSecretManagerClient.java
> +@Requires(property = "gcp.secret-manager.location")
extract this property reference into a constant.

2024-10-23 14:41 UTC, graemerocher commented on gcp-secret-manager/src/main/java/io/micronaut/gcp/secretmanager/client/DefaultLocationSecretManagerClient.java
> +            @Nullable @Named(TaskExecutors.IO) ExecutorService executorService,
use `TaskExecutors.BLOCKING`

2024-10-23 14:41 UTC, graemerocher commented on gcp-secret-manager/src/main/java/io/micronaut/gcp/secretmanager/client/DefaultSecretManagerClient.java
> +@Requires(missingProperty = "gcp.secret-manager.location")
reuse constant here

2024-10-23 14:41 UTC, graemerocher commented on gcp-secret-manager/src/main/java/io/micronaut/gcp/secretmanager/client/DefaultLocationSecretManagerClient.java
> +                .onErrorResume(throwable -> Mono.empty());
don't just swallow the exception but add some debug logging here

2024-10-24 09:38 UTC, abheda-crest commented on gcp-secret-manager/src/main/java/io/micronaut/gcp/secretmanager/client/DefaultLocationSecretManagerClient.java
> +@Requires(property = "gcp.secret-manager.location")
I updated the code to utilize the existing constant `PREFIX` from the `SecretManagerConfigurationProperties` class and concatenate it with the location property suffix, `.location`.

A similar approach has been applied in a few other instances:
- https://github.com/micronaut-projects/micronaut-gcp/blob/5.7.x/gcp-common/src/main/java/io/micronaut/discovery/cloud/gcp/GoogleComputeInstanceMetadataResolver.java#L56C22-L56C56
- https://github.com/micronaut-projects/micronaut-gcp/blob/5.7.x/gcp-common/src/main/java/io/micronaut/gcp/credentials/GoogleCredentialsFactory.java#L101
- https://github.com/micronaut-projects/micronaut-gcp/blob/5.7.x/gcp-common/src/main/java/io/micronaut/gcp/credentials/DefaultOAuth2HttpTransportFactory.java#L59

Let me know if this need any change.

2024-10-24 09:38 UTC, abheda-crest commented on gcp-secret-manager/src/main/java/io/micronaut/gcp/secretmanager/client/DefaultLocationSecretManagerClient.java
> +            @Nullable @Named(TaskExecutors.IO) ExecutorService executorService,
Done

2024-10-24 09:40 UTC, abheda-crest commented on gcp-secret-manager/src/main/java/io/micronaut/gcp/secretmanager/client/DefaultSecretManagerClient.java
> +@Requires(missingProperty = "gcp.secret-manager.location")
Same as the above [comment.](https://github.com/micronaut-projects/micronaut-gcp/pull/1202#discussion_r1814643642)

2024-10-24 09:41 UTC, abheda-crest commented on gcp-secret-manager/src/main/java/io/micronaut/gcp/secretmanager/client/DefaultLocationSecretManagerClient.java
> +                .onErrorResume(throwable -> Mono.empty());
Done

2024-10-24 09:42 UTC, graemerocher approved these changes

2024-10-24 15:30 UTC, sdelamo approved these changes
Thanks for the contribution @abheda-crest. 

I have pushed some small changes: 

- [Decrete the empty constructor of `SecretManagerFactory`](https://github.com/micronaut-projects/micronaut-gcp/pull/1202/commits/c44182ac620560e21c1665792343ede7b876d5b9)
- [Keep a single DefaultSecretManagerClient](https://github.com/micronaut-projects/micronaut-gcp/pull/1202/commits/5f43c3973ebedf6ffb8a719379b7ebaf58b18bf5)
- [Add a regex pattern for the locations](https://github.com/micronaut-projects/micronaut-gcp/pull/1202/commits/3802fabe2d76fd2c2bf5b6e584d6177999cacd23)
- [Made Groovy code in tests a little bit more idiomatic](https://github.com/micronaut-projects/micronaut-gcp/pull/1202/commits/a7e383467666f9b28cfd021d14e8f5691b1562fb)
- [Add some nullability and javadoc info tags](https://github.com/micronaut-projects/micronaut-gcp/pull/1202/commits/9da1875268fc34133bfac5a34f09f6b3e53e5bba). 
- [Small copy corrections](https://github.com/micronaut-projects/micronaut-gcp/pull/1202/commits/17245e3591113b564ca763f219d4267c0539d007). 

I hope you don't mind. Again, thanks for the contribution.

2024-10-24 15:30 UTC, sdelamo commented on gcp-secret-manager/src/main/java/io/micronaut/gcp/secretmanager/SecretManagerFactory.java
> +            if (configurationProperties != null && !StringUtils.isEmpty(configurationProperties.getLocation())) {
```suggestion
            if (configurationProperties != null && StringUtils.isNotEmpty(configurationProperties.getLocation())) {
```

2024-10-24 15:30 UTC, sdelamo commented on gcp-secret-manager/src/main/java/io/micronaut/gcp/secretmanager/SecretManagerFactory.java
> +    public SecretManagerFactory(SecretManagerConfigurationProperties configurationProperties) {
We need to keep the old constructor and deprecate it.

2024-10-24 15:30 UTC, sdelamo commented on gcp-secret-manager/src/main/java/io/micronaut/gcp/secretmanager/client/DefaultLocationSecretManagerClient.java
> + * @author Alfatah Bheda
```suggestion
 * @author Alfatah Bheda
 * @since 5.8.0
```

2024-10-24 15:30 UTC, sdelamo commented on gcp-secret-manager/src/main/java/io/micronaut/gcp/secretmanager/client/DefaultLocationSecretManagerClient.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(DefaultLocationSecretManagerClient.class);
rename `LOGGER` to `LOG` to be consistent with the framework.

2024-10-24 15:30 UTC, sdelamo commented on gcp-secret-manager/src/main/java/io/micronaut/gcp/secretmanager/client/DefaultLocationSecretManagerClient.java
> +public class DefaultLocationSecretManagerClient implements SecretManagerClient {
I think it would be better to keep a single implementation of `SecretManagerClient`

2024-10-25 04:47 UTC, merged