Adding support to Distributed Configuration via Google Cloud Secret Manager
micronaut-projects/micronaut-gcp pull request #324
Opened 2020-12-03 20:05 UTC by viniciusccarvalho

Long overdue, life got in the way.

Looking forward for reviews and improvements

Fixed a few typos on the GCP docs as well

Some of the gcp-common beans had to be annotated with `@BootstrapContextCompatible`

2020-12-03 23:29 UTC, viniciusccarvalho commented
I can't tell why the check fails on the runner, and not on my machine. I think I ran the same build `./gradlew check`, it looks like the checkstyle rules are different and way more strict than the ones on the project.

For instance:

```
Error: eckstyle] [ERROR] /home/runner/work/micronaut-gcp/micronaut-gcp/gcp-logging/src/main/java/io/micronaut/gcp/logging/GoogleCloudPropertyDefiner.java:41:61: http:// URLs are not allowed but got 'http://metadata.google.internal'. Use https:// instead. [NoHttp]```

That is a string declaration for the google cloud metadata server that happens to not be available on `https` seems to be a very strict checkstyle rule.

Let me know what needs to be done for the tests to pass.

Cheers

2020-12-04 10:13 UTC, alvarosanchez commented
@viniciusccarvalho you can disable checkstyle on a per-line basis wrapping them with

```java
//CHECKSTYLE:OFF
...
//CHECKSTYLE:ON
```

2020-12-04 13:32 UTC, viniciusccarvalho commented
Thanks @alvarosanchez I'm still intrigued by two things:

1. The offending class is on the logging module, not part of this PR, did the checkstyle rules changed?
2. On my machine the build passes with no warning, I have forced checkstyleMain, check, and they all pass with no warning. Still not clear where the checkstyle warnings are coming from.

2020-12-04 16:09 UTC, alvarosanchez commented
It is actually my fault, when merging #315 I inadvertently reverted the change to use only Java 11.

I'm so sorry 🙏 

I'll fix it in master and rebase your PR

2020-12-04 16:25 UTC, alvarosanchez commented
Ok, now it works. The actions failure is because of https://github.com/micronaut-projects/micronaut-project-template/issues/62, and can be ignored.

Apart from that, is this ready for review?

2020-12-04 16:42 UTC, viniciusccarvalho commented
It should be thank you!

2020-12-09 09:57 UTC, graemerocher requested changes
Just a couple of minor things. Nice work!

2020-12-09 09:57 UTC, graemerocher commented on gcp-secret-manager/src/main/resources/logback.xml
> +</configuration>
This shouldn't be in `src/main/resources`. Maybe you meant `src/test/resourses`?

2020-12-09 09:57 UTC, graemerocher commented on gcp-secret-manager/src/main/java/io/micronaut/gcp/secretmanager/configuration/SecretManagerConfigurationProperties.java
> +
Does order not matter for these configs?

2020-12-10 08:19 UTC, graemerocher approved these changes

2020-12-10 08:20 UTC, graemerocher commented
@ilopmar @alvarosanchez when this is merged and the BOM updated for 2.3.x please add an entry in the what's new docs crediting @viniciusccarvalho work for 2.3.x

Thanks @viniciusccarvalho !

2020-12-10 10:52 UTC, merged

2020-12-10 10:54 UTC, alvarosanchez commented
Thank you very much @viniciusccarvalho! I have in fact invited you as a collaborator to this repo, so no more need to work on your fork.

2020-12-10 14:53 UTC, viniciusccarvalho commented
Thank you folks, it's been an amazing journey being able to contribute to this amazing framework. Truly humbled to be learn more every day from you all :)