[gcp] Update common files for branch master
micronaut-projects/micronaut-gcp pull request #961
Opened 2023-10-13 05:22 UTC by micronaut-build

Update common files

2023-10-17 10:48 UTC, timyates requested changes

2023-10-17 10:48 UTC, timyates commented on test-suite-kotlin/build.gradle
> +    kotlinOptions.languageVersion = "1.7"
why languageVersion as well?

2023-10-17 14:33 UTC, wetted commented on test-suite-kotlin/build.gradle
> +    kotlinOptions.languageVersion = "1.7"
I copied it from another example. 🤷‍♂️

2023-10-18 11:06 UTC, timyates commented
Closing this in favor of https://github.com/micronaut-projects/micronaut-gcp/pull/967 to stop force-push nightmares

2023-10-18 11:06 UTC, closed without merging